"""Add users, goods, and categories tables

Revision ID: e93ca8696754
Revises: c5cdf6d8a021
Create Date: 2024-11-23 22:12:21.631302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93ca8696754'
down_revision: Union[str, None] = 'c5cdf6d8a021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
